### PR TITLE
Create Maximum xor of two number in array.cpp

### PR DESCRIPTION
**Pull request by Heartlessplaye**
-> using trie

### CODE REVIEW

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `_contributor name.txt_` if not found your name in `_contributor name.txt_` it should be Labelled as **SPAM**.
STAR 🌟 this REPO for future HacktoberFest.

**Comment by Romi904** [comment]
If our team not found your name in follow list then u may be labelled as INVALID.

**Comment by Heartlessplaye** [comment]
Done

**Comment by Romi904** [comment]
and then send new PR

**Pull request closed without merging**
