### PR TITLE
Updated CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by shubhamnegi9**
[Updated CONTRIBUTING.md file]

### CODE REVIEW

**Comment by Romi904** [comment]
You have a Conflict Resolve the issue first.

**Comment by shubhamnegi9** [comment]
Resolved the merge conflicts

**Comment by Romi904** [comment]
Done  Labelled

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `_contributing.md` if not found your name in `_contributing.md` it should be Labelled as **SPAM**.
STAR 🌟 this REPO for future HacktoberFest.
<a href="https://t.me/hacktoberfest022"></a>

**Pull request merged**
