### PR TITLE
Quiz App

### PR DESCRIPTION
**Pull request by aditi10701**
A quiz App added to the repository. Kindly consider this and suggest changes if required.

### CODE REVIEW

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `contributing.md` if not found your name in `contributing.md` it should be Labelled as **SPAM**.
STAR 🌟 this REPO for future HacktoberFest.

**Comment by aditi10701** [comment]
> ### ATTENTION 🚨🚨🚨
> Don’t Forget To Follow Me On Github , and Add Your Name In `contributing.md` if not found your name in `contributing.md` it should be Labelled as **SPAM**. STAR 🌟 this REPO for future HacktoberFest.

Followed on github. Updated the file. kindly approve the full request.

**Comment by aditi10701** [comment]
Is it now considered under hacktoberfest?
It's showing as excluded?
Is there any other step which needs to be done?

**Comment by Romi904** [comment]
nah, this repo is reported by someone.

**Pull request merged**
