### PR TITLE
Create Countdown Timer Using PHP & Resolve conflicts

### PR DESCRIPTION
**Pull request by giovannikurniawan**

### CODE REVIEW

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `_contributing.md` if not found your name in `_contributing.md` it should be Labelled as **SPAM**.
STAR 🌟 this REPO for future HacktoberFest.
<a href="https://t.me/hacktoberfest022"></a>

**Comment by Romi904** [comment]
Dont Forget to Follow and add ur name.

**Comment by Romi904** [comment]
Our team found that after 8 hours u r not following our guideline that's why u labelled as SPAM.

**Comment by giovannikurniawan** [comment]
why spam? I have followed the existing rules, please check again thanks

**Comment by Romi904** [comment]
You Haven't Followed us that's why SPAM.
If u have followed us the give us screenshot of that window, because our team unable to find your name in followers list.
Thanks

**Comment by giovannikurniawan** [comment]
Screenshot_1
Screenshot_2

**Comment by Romi904** [comment]
then why your name is not found in our list.
ok By the way .
Thanks

**Pull request merged**
