### PR TITLE
Added Java Program

### PR DESCRIPTION
**Pull request by ishubham010**
Successfully added a Java Program to find the frequency of each element in the array. Please accept my commit.

### CODE REVIEW

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `_contributing.md` if not found your name in `_contributing.md` it should be Labelled as **SPAM**.
STAR 🌟 this REPO for future HacktoberFest.
<a href="https://t.me/hacktoberfest022"></a>

**Comment by Romi904** [comment]
Please Resolve the conflict

**Comment by ishubham010** [comment]
Yes, already added name in contribution list.

**Comment by Romi904** [comment]
No You have a Conflict with the branches resolve that issue first, otherwise we may close this issue.

**Comment by ishubham010** [comment]
I have resolved the conflict please merge.

**Comment by Romi904** [comment]
image

**Comment by Romi904** [comment]
REsolve the conflict

**Comment by ishubham010** [comment]
conflict
**Hope this time it's working perfect** 👍

**Comment by Romi904** [comment]
ya,now it's ok
let our tem to check ur code

**Comment by Romi904** [comment]
our team found that u haven't followed us ??

**Comment by ishubham010** [comment]
Yes done

**Pull request merged**
