### PR TITLE
added tipCahculator

### PR DESCRIPTION
**Pull request by yashgoel2211**

### CODE REVIEW

**Comment by yashgoel2211** [comment]
added TipCalculator

**Comment by Romi904** [comment]
Attach a screenshot

**Comment by Romi904** [comment]
scre

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `_contributor name.txt_` if not found your name in `_contributor name.txt_` it should be Labelled as **SPAM**.
STAR 🌟 this REPO for future HacktoberFest.

**Pull request merged**
