### PR TITLE
Create replace lowercase characters with uppercase

### PR DESCRIPTION
**Pull request by raju121097**
In this PR, I have written the code for replacing lower case character with uppercase and uppercase characters with lowercase.

Please review and merge.

### CODE REVIEW

**Review by Romi904 — COMMENTED** [review]
I Found some ERROR in your code, can u attach a screenshot of terminal window.

**Comment by Romi904** [comment]
scre

**Comment by raju121097** [comment]
output
PFA picture of output

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `_contributor name.txt_` if not found your name in `_contributor name.txt_` it should be Labelled as **SPAM**.

**Pull request merged**
