### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by pulkit-999**
create solution for edit distance problem

### CODE REVIEW

**Review by Romi904 — APPROVED** [review]
Approved

**Comment by pulkit-999** [comment]
label as hactober fest?

**Comment by Romi904** [comment]
Done the above task and then ping me as 'DONE'

**Comment by pulkit-999** [comment]
DONE

**Comment by Romi904** [comment]
👍

**Comment by pulkit-999** [comment]
Thanks

**Pull request merged**
