### PR TITLE
Added files for the AVL Tree

### PR DESCRIPTION
**Pull request by harshvardhan2804**
I have added files for the AVL tree implementation. 
It contains an insert and deletes function along with rotations.

### CODE REVIEW

**Comment by Romi904** [comment]
resolve the conflicts

**Comment by harshvardhan2804** [comment]
> resolve the conflicts

conflicts have been resolved.

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `_contributing.md` if not found your name in `_contributing.md` it should be Labelled as **SPAM**.
STAR 🌟 this REPO for future HacktoberFest.
<a href="https://t.me/hacktoberfest022"></a>

**Comment by Romi904** [comment]
when u complete the task comment as DONE

**Comment by harshvardhan2804** [comment]
> when u complete the task comment as DONE

Done

**Pull request merged**
