### PR TITLE
Add Longest_Alternating_Subsequence

### PR DESCRIPTION
**Pull request by aryangupta899**
Kindly merge this, for hacktoberfest

### CODE REVIEW

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `_contributor name.txt_` if not found your name in `_contributor name.txt_` it should be Labelled as **SPAM**.
STAR 🌟 this REPO for future HacktoberFest.

**Comment by aryangupta899** [comment]
> ### ATTENTION 🚨🚨🚨
> Don’t Forget To Follow Me On Github , and Add Your Name In `_contributor name.txt_` if not found your name in `_contributor name.txt_` it should be Labelled as **SPAM**. STAR 🌟 this REPO for future HacktoberFest.

Hi @Romi904 I am not able to update my name in the Contributors. It says permission to your repo is denied!

**Comment by Romi904** [comment]
Okay,let our team to check the issue.

**Comment by Romi904** [comment]
Your Name IS Present In the `contributor name.txt` file.

**Pull request merged**
