### PR TITLE
Added Space invader game

### PR DESCRIPTION
**Pull request by rahulranjan74**
using pygame
added important images

### CODE REVIEW

**Comment by Romi904** [comment]
### ATTENTION 🚨🚨🚨
Don’t Forget To Follow Me On Github , and Add Your Name In `_contributing.md` if not found your name in `_contributing.md` it should be Labelled as **SPAM**.
STAR 🌟 this REPO for future HacktoberFest.

**Comment by rahulranjan74** [comment]
done

**Comment by Romi904** [comment]
Hey iam opening a issue to your repo,
pls close it as complete after 2 min.
is it ok?

**Comment by Romi904** [comment]
let us know when u came online.

**Comment by rahulranjan74** [comment]
okay , what should i do?

**Comment by Romi904** [comment]
are you online ?

**Comment by rahulranjan74** [comment]
yes

**Comment by Romi904** [comment]
iam opening an issue to your repo okay, and after 2 min yuo need to be comment as completed and closed as complete.

**Comment by rahulranjan74** [comment]
so i need to comment - "COMPLETED" and close it after 2 minutes right?? understood

**Comment by Romi904** [comment]
yes

**Comment by rahulranjan74** [comment]
i will close it as completed after 2 min

**Comment by Romi904** [comment]
thanks

**Comment by rahulranjan74** [comment]
has my pull request accepted @Romi904 ?

**Comment by Romi904** [comment]
Yes, Your PR is accepted.

**Comment by Romi904** [comment]
You can reach me at -  https://t.me/hacktoberfest022

**Comment by rahulranjan74** [comment]
Okay was just confirming beacuse it was showing in hacktober site...might be updated later..thanks!

**Comment by Romi904** [comment]
it takes 15min to update

**Comment by rahulranjan74** [comment]
Got it

**Pull request merged**
